export const PERSONAL_DATA_SCHEMA = {
  type: 'https://schema.org/Person',
  name: 'https://schema.org/name',
  image: 'https://schema.org/image',
  birthdate: 'https://schema.org/birthDate',
  address: 'https://schema.org/address',
  phone: 'https://schema.org/telephone',
  email: 'https://schema.org/email',
  nation: 'https://schema.org/nation',
  height: 'https://schema.org/height',
  weight: 'https://schema.org/weight',
  dominantFoot: 'https://schema.org/dominantFoot',
  team: 'https://schema.org/team',
  league: 'https://schema.org/league',
  position: 'https://schema.org/position',
};
