/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as dashboardImport } from './routes/__dashboard'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as dashboardIndexImport } from './routes/__dashboard/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthConfirmationImport } from './routes/auth/confirmation'
import { Route as AuthCallbackImport } from './routes/auth/callback'
import { Route as AuthSetupImport } from './routes/auth/_setup'
import { Route as dashboardTrackingDataImport } from './routes/__dashboard/tracking-data'
import { Route as dashboardProfileImport } from './routes/__dashboard/profile'
import { Route as dashboardPersonalDataImport } from './routes/__dashboard/personal-data'
import { Route as dashboardInboxImport } from './routes/__dashboard/inbox'
import { Route as dashboardFootballDataImport } from './routes/__dashboard/football-data'
import { Route as dashboardAccessHistoryImport } from './routes/__dashboard/access-history'
import { Route as dashboardAccessControlImport } from './routes/__dashboard/access-control'
import { Route as AuthSetupTeamImport } from './routes/auth/_setup.team'
import { Route as AuthSetupProfileImport } from './routes/auth/_setup.profile'
import { Route as dashboardTeamMembersImport } from './routes/__dashboard/team/members'
import { Route as dashboardTeamDetailsImport } from './routes/__dashboard/team/details'
import { Route as dashboardSeasonsSeasonImport } from './routes/__dashboard/seasons.$season'
import { Route as dashboardMatchesMatchImport } from './routes/__dashboard/matches.$match'

// Create/Update Routes

const dashboardRoute = dashboardImport.update({
  id: '/__dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const dashboardIndexRoute = dashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthConfirmationRoute = AuthConfirmationImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSetupRoute = AuthSetupImport.update({
  id: '/_setup',
  getParentRoute: () => AuthRouteRoute,
} as any)

const dashboardTrackingDataRoute = dashboardTrackingDataImport.update({
  id: '/tracking-data',
  path: '/tracking-data',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardProfileRoute = dashboardProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardPersonalDataRoute = dashboardPersonalDataImport.update({
  id: '/personal-data',
  path: '/personal-data',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardInboxRoute = dashboardInboxImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardFootballDataRoute = dashboardFootballDataImport.update({
  id: '/football-data',
  path: '/football-data',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardAccessHistoryRoute = dashboardAccessHistoryImport.update({
  id: '/access-history',
  path: '/access-history',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardAccessControlRoute = dashboardAccessControlImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => dashboardRoute,
} as any)

const AuthSetupTeamRoute = AuthSetupTeamImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthSetupRoute,
} as any)

const AuthSetupProfileRoute = AuthSetupProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSetupRoute,
} as any)

const dashboardTeamMembersRoute = dashboardTeamMembersImport.update({
  id: '/team/members',
  path: '/team/members',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardTeamDetailsRoute = dashboardTeamDetailsImport.update({
  id: '/team/details',
  path: '/team/details',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardSeasonsSeasonRoute = dashboardSeasonsSeasonImport.update({
  id: '/seasons/$season',
  path: '/seasons/$season',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardMatchesMatchRoute = dashboardMatchesMatchImport.update({
  id: '/matches/$match',
  path: '/matches/$match',
  getParentRoute: () => dashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/__dashboard': {
      id: '/__dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardImport
      parentRoute: typeof rootRoute
    }
    '/__dashboard/access-control': {
      id: '/__dashboard/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof dashboardAccessControlImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/access-history': {
      id: '/__dashboard/access-history'
      path: '/access-history'
      fullPath: '/access-history'
      preLoaderRoute: typeof dashboardAccessHistoryImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/football-data': {
      id: '/__dashboard/football-data'
      path: '/football-data'
      fullPath: '/football-data'
      preLoaderRoute: typeof dashboardFootballDataImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/inbox': {
      id: '/__dashboard/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof dashboardInboxImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/personal-data': {
      id: '/__dashboard/personal-data'
      path: '/personal-data'
      fullPath: '/personal-data'
      preLoaderRoute: typeof dashboardPersonalDataImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/profile': {
      id: '/__dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof dashboardProfileImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/tracking-data': {
      id: '/__dashboard/tracking-data'
      path: '/tracking-data'
      fullPath: '/tracking-data'
      preLoaderRoute: typeof dashboardTrackingDataImport
      parentRoute: typeof dashboardImport
    }
    '/auth/_setup': {
      id: '/auth/_setup'
      path: ''
      fullPath: '/auth'
      preLoaderRoute: typeof AuthSetupImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/confirmation': {
      id: '/auth/confirmation'
      path: '/confirmation'
      fullPath: '/auth/confirmation'
      preLoaderRoute: typeof AuthConfirmationImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRouteImport
    }
    '/__dashboard/': {
      id: '/__dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/matches/$match': {
      id: '/__dashboard/matches/$match'
      path: '/matches/$match'
      fullPath: '/matches/$match'
      preLoaderRoute: typeof dashboardMatchesMatchImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/seasons/$season': {
      id: '/__dashboard/seasons/$season'
      path: '/seasons/$season'
      fullPath: '/seasons/$season'
      preLoaderRoute: typeof dashboardSeasonsSeasonImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/team/details': {
      id: '/__dashboard/team/details'
      path: '/team/details'
      fullPath: '/team/details'
      preLoaderRoute: typeof dashboardTeamDetailsImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/team/members': {
      id: '/__dashboard/team/members'
      path: '/team/members'
      fullPath: '/team/members'
      preLoaderRoute: typeof dashboardTeamMembersImport
      parentRoute: typeof dashboardImport
    }
    '/auth/_setup/profile': {
      id: '/auth/_setup/profile'
      path: '/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthSetupProfileImport
      parentRoute: typeof AuthSetupImport
    }
    '/auth/_setup/team': {
      id: '/auth/_setup/team'
      path: '/team'
      fullPath: '/auth/team'
      preLoaderRoute: typeof AuthSetupTeamImport
      parentRoute: typeof AuthSetupImport
    }
  }
}

// Create and export the route tree

interface AuthSetupRouteChildren {
  AuthSetupProfileRoute: typeof AuthSetupProfileRoute
  AuthSetupTeamRoute: typeof AuthSetupTeamRoute
}

const AuthSetupRouteChildren: AuthSetupRouteChildren = {
  AuthSetupProfileRoute: AuthSetupProfileRoute,
  AuthSetupTeamRoute: AuthSetupTeamRoute,
}

const AuthSetupRouteWithChildren = AuthSetupRoute._addFileChildren(
  AuthSetupRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSetupRoute: typeof AuthSetupRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmationRoute: typeof AuthConfirmationRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSetupRoute: AuthSetupRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmationRoute: AuthConfirmationRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface dashboardRouteChildren {
  dashboardAccessControlRoute: typeof dashboardAccessControlRoute
  dashboardAccessHistoryRoute: typeof dashboardAccessHistoryRoute
  dashboardFootballDataRoute: typeof dashboardFootballDataRoute
  dashboardInboxRoute: typeof dashboardInboxRoute
  dashboardPersonalDataRoute: typeof dashboardPersonalDataRoute
  dashboardProfileRoute: typeof dashboardProfileRoute
  dashboardTrackingDataRoute: typeof dashboardTrackingDataRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardMatchesMatchRoute: typeof dashboardMatchesMatchRoute
  dashboardSeasonsSeasonRoute: typeof dashboardSeasonsSeasonRoute
  dashboardTeamDetailsRoute: typeof dashboardTeamDetailsRoute
  dashboardTeamMembersRoute: typeof dashboardTeamMembersRoute
}

const dashboardRouteChildren: dashboardRouteChildren = {
  dashboardAccessControlRoute: dashboardAccessControlRoute,
  dashboardAccessHistoryRoute: dashboardAccessHistoryRoute,
  dashboardFootballDataRoute: dashboardFootballDataRoute,
  dashboardInboxRoute: dashboardInboxRoute,
  dashboardPersonalDataRoute: dashboardPersonalDataRoute,
  dashboardProfileRoute: dashboardProfileRoute,
  dashboardTrackingDataRoute: dashboardTrackingDataRoute,
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardMatchesMatchRoute: dashboardMatchesMatchRoute,
  dashboardSeasonsSeasonRoute: dashboardSeasonsSeasonRoute,
  dashboardTeamDetailsRoute: dashboardTeamDetailsRoute,
  dashboardTeamMembersRoute: dashboardTeamMembersRoute,
}

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(
  dashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthSetupRouteWithChildren
  '': typeof dashboardRouteWithChildren
  '/access-control': typeof dashboardAccessControlRoute
  '/access-history': typeof dashboardAccessHistoryRoute
  '/football-data': typeof dashboardFootballDataRoute
  '/inbox': typeof dashboardInboxRoute
  '/personal-data': typeof dashboardPersonalDataRoute
  '/profile': typeof dashboardProfileRoute
  '/tracking-data': typeof dashboardTrackingDataRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirmation': typeof AuthConfirmationRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof dashboardIndexRoute
  '/matches/$match': typeof dashboardMatchesMatchRoute
  '/seasons/$season': typeof dashboardSeasonsSeasonRoute
  '/team/details': typeof dashboardTeamDetailsRoute
  '/team/members': typeof dashboardTeamMembersRoute
  '/auth/profile': typeof AuthSetupProfileRoute
  '/auth/team': typeof AuthSetupTeamRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthSetupRouteWithChildren
  '/access-control': typeof dashboardAccessControlRoute
  '/access-history': typeof dashboardAccessHistoryRoute
  '/football-data': typeof dashboardFootballDataRoute
  '/inbox': typeof dashboardInboxRoute
  '/personal-data': typeof dashboardPersonalDataRoute
  '/profile': typeof dashboardProfileRoute
  '/tracking-data': typeof dashboardTrackingDataRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirmation': typeof AuthConfirmationRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof dashboardIndexRoute
  '/matches/$match': typeof dashboardMatchesMatchRoute
  '/seasons/$season': typeof dashboardSeasonsSeasonRoute
  '/team/details': typeof dashboardTeamDetailsRoute
  '/team/members': typeof dashboardTeamMembersRoute
  '/auth/profile': typeof AuthSetupProfileRoute
  '/auth/team': typeof AuthSetupTeamRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/__dashboard': typeof dashboardRouteWithChildren
  '/__dashboard/access-control': typeof dashboardAccessControlRoute
  '/__dashboard/access-history': typeof dashboardAccessHistoryRoute
  '/__dashboard/football-data': typeof dashboardFootballDataRoute
  '/__dashboard/inbox': typeof dashboardInboxRoute
  '/__dashboard/personal-data': typeof dashboardPersonalDataRoute
  '/__dashboard/profile': typeof dashboardProfileRoute
  '/__dashboard/tracking-data': typeof dashboardTrackingDataRoute
  '/auth/_setup': typeof AuthSetupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirmation': typeof AuthConfirmationRoute
  '/auth/login': typeof AuthLoginRoute
  '/__dashboard/': typeof dashboardIndexRoute
  '/__dashboard/matches/$match': typeof dashboardMatchesMatchRoute
  '/__dashboard/seasons/$season': typeof dashboardSeasonsSeasonRoute
  '/__dashboard/team/details': typeof dashboardTeamDetailsRoute
  '/__dashboard/team/members': typeof dashboardTeamMembersRoute
  '/auth/_setup/profile': typeof AuthSetupProfileRoute
  '/auth/_setup/team': typeof AuthSetupTeamRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | ''
    | '/access-control'
    | '/access-history'
    | '/football-data'
    | '/inbox'
    | '/personal-data'
    | '/profile'
    | '/tracking-data'
    | '/auth/callback'
    | '/auth/confirmation'
    | '/auth/login'
    | '/'
    | '/matches/$match'
    | '/seasons/$season'
    | '/team/details'
    | '/team/members'
    | '/auth/profile'
    | '/auth/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/access-control'
    | '/access-history'
    | '/football-data'
    | '/inbox'
    | '/personal-data'
    | '/profile'
    | '/tracking-data'
    | '/auth/callback'
    | '/auth/confirmation'
    | '/auth/login'
    | '/'
    | '/matches/$match'
    | '/seasons/$season'
    | '/team/details'
    | '/team/members'
    | '/auth/profile'
    | '/auth/team'
  id:
    | '__root__'
    | '/auth'
    | '/__dashboard'
    | '/__dashboard/access-control'
    | '/__dashboard/access-history'
    | '/__dashboard/football-data'
    | '/__dashboard/inbox'
    | '/__dashboard/personal-data'
    | '/__dashboard/profile'
    | '/__dashboard/tracking-data'
    | '/auth/_setup'
    | '/auth/callback'
    | '/auth/confirmation'
    | '/auth/login'
    | '/__dashboard/'
    | '/__dashboard/matches/$match'
    | '/__dashboard/seasons/$season'
    | '/__dashboard/team/details'
    | '/__dashboard/team/members'
    | '/auth/_setup/profile'
    | '/auth/_setup/team'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  dashboardRoute: typeof dashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  dashboardRoute: dashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/auth",
        "/__dashboard"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/_setup",
        "/auth/callback",
        "/auth/confirmation",
        "/auth/login"
      ]
    },
    "/__dashboard": {
      "filePath": "__dashboard.tsx",
      "children": [
        "/__dashboard/access-control",
        "/__dashboard/access-history",
        "/__dashboard/football-data",
        "/__dashboard/inbox",
        "/__dashboard/personal-data",
        "/__dashboard/profile",
        "/__dashboard/tracking-data",
        "/__dashboard/",
        "/__dashboard/matches/$match",
        "/__dashboard/seasons/$season",
        "/__dashboard/team/details",
        "/__dashboard/team/members"
      ]
    },
    "/__dashboard/access-control": {
      "filePath": "__dashboard/access-control.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/access-history": {
      "filePath": "__dashboard/access-history.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/football-data": {
      "filePath": "__dashboard/football-data.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/inbox": {
      "filePath": "__dashboard/inbox.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/personal-data": {
      "filePath": "__dashboard/personal-data.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/profile": {
      "filePath": "__dashboard/profile.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/tracking-data": {
      "filePath": "__dashboard/tracking-data.tsx",
      "parent": "/__dashboard"
    },
    "/auth/_setup": {
      "filePath": "auth/_setup.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_setup/profile",
        "/auth/_setup/team"
      ]
    },
    "/auth/callback": {
      "filePath": "auth/callback.tsx",
      "parent": "/auth"
    },
    "/auth/confirmation": {
      "filePath": "auth/confirmation.tsx",
      "parent": "/auth"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/__dashboard/": {
      "filePath": "__dashboard/index.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/matches/$match": {
      "filePath": "__dashboard/matches.$match.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/seasons/$season": {
      "filePath": "__dashboard/seasons.$season.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/team/details": {
      "filePath": "__dashboard/team/details.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/team/members": {
      "filePath": "__dashboard/team/members.tsx",
      "parent": "/__dashboard"
    },
    "/auth/_setup/profile": {
      "filePath": "auth/_setup.profile.tsx",
      "parent": "/auth/_setup"
    },
    "/auth/_setup/team": {
      "filePath": "auth/_setup.team.tsx",
      "parent": "/auth/_setup"
    }
  }
}
ROUTE_MANIFEST_END */
