/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as dashboardImport } from './routes/__dashboard'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as dashboardIndexImport } from './routes/__dashboard/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthConfirmationImport } from './routes/auth/confirmation'
import { Route as AuthCallbackImport } from './routes/auth/callback'
import { Route as AuthSetupImport } from './routes/auth/_setup'
import { Route as dashboardSettingsImport } from './routes/__dashboard/settings'
import { Route as dashboardProfileImport } from './routes/__dashboard/profile'
import { Route as dashboardInboxImport } from './routes/__dashboard/inbox'
import { Route as dashboardAccessHistoryImport } from './routes/__dashboard/access-history'
import { Route as dashboardAccessControlImport } from './routes/__dashboard/access-control'
import { Route as AuthSetupTeamImport } from './routes/auth/_setup.team'
import { Route as AuthSetupProfileImport } from './routes/auth/_setup.profile'
import { Route as dashboardTeamOutsourcingImport } from './routes/__dashboard/team/outsourcing'
import { Route as dashboardTeamDetailsImport } from './routes/__dashboard/team/details'
import { Route as dashboardFileUrlImport } from './routes/__dashboard/file/$url'
import { Route as dashboardPlayerPodCategoryImport } from './routes/__dashboard/player/$pod/$category'
import { Route as dashboardDeprecatedPlayerPodImport } from './routes/__dashboard/deprecated/player/$pod'
import { Route as dashboardDeprecatedPlayerPodTrackingDataImport } from './routes/__dashboard/deprecated/player/$pod/tracking-data'
import { Route as dashboardDeprecatedPlayerPodPersonalDataImport } from './routes/__dashboard/deprecated/player/$pod/personal-data'
import { Route as dashboardDeprecatedPlayerPodHealthDataImport } from './routes/__dashboard/deprecated/player/$pod/health-data'
import { Route as dashboardDeprecatedPlayerPodFootballDataImport } from './routes/__dashboard/deprecated/player/$pod/football-data'
import { Route as dashboardDeprecatedPlayerPodSeasonsSeasonImport } from './routes/__dashboard/deprecated/player/$pod/seasons.$season'
import { Route as dashboardDeprecatedPlayerPodMatchesMatchImport } from './routes/__dashboard/deprecated/player/$pod/matches.$match'

// Create/Update Routes

const dashboardRoute = dashboardImport.update({
  id: '/__dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const dashboardIndexRoute = dashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthConfirmationRoute = AuthConfirmationImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSetupRoute = AuthSetupImport.update({
  id: '/_setup',
  getParentRoute: () => AuthRouteRoute,
} as any)

const dashboardSettingsRoute = dashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardProfileRoute = dashboardProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardInboxRoute = dashboardInboxImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardAccessHistoryRoute = dashboardAccessHistoryImport.update({
  id: '/access-history',
  path: '/access-history',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardAccessControlRoute = dashboardAccessControlImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => dashboardRoute,
} as any)

const AuthSetupTeamRoute = AuthSetupTeamImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthSetupRoute,
} as any)

const AuthSetupProfileRoute = AuthSetupProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSetupRoute,
} as any)

const dashboardTeamOutsourcingRoute = dashboardTeamOutsourcingImport.update({
  id: '/team/outsourcing',
  path: '/team/outsourcing',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardTeamDetailsRoute = dashboardTeamDetailsImport.update({
  id: '/team/details',
  path: '/team/details',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardFileUrlRoute = dashboardFileUrlImport.update({
  id: '/file/$url',
  path: '/file/$url',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardPlayerPodCategoryRoute = dashboardPlayerPodCategoryImport.update(
  {
    id: '/player/$pod/$category',
    path: '/player/$pod/$category',
    getParentRoute: () => dashboardRoute,
  } as any,
)

const dashboardDeprecatedPlayerPodRoute =
  dashboardDeprecatedPlayerPodImport.update({
    id: '/deprecated/player/$pod',
    path: '/deprecated/player/$pod',
    getParentRoute: () => dashboardRoute,
  } as any)

const dashboardDeprecatedPlayerPodTrackingDataRoute =
  dashboardDeprecatedPlayerPodTrackingDataImport.update({
    id: '/tracking-data',
    path: '/tracking-data',
    getParentRoute: () => dashboardDeprecatedPlayerPodRoute,
  } as any)

const dashboardDeprecatedPlayerPodPersonalDataRoute =
  dashboardDeprecatedPlayerPodPersonalDataImport.update({
    id: '/personal-data',
    path: '/personal-data',
    getParentRoute: () => dashboardDeprecatedPlayerPodRoute,
  } as any)

const dashboardDeprecatedPlayerPodHealthDataRoute =
  dashboardDeprecatedPlayerPodHealthDataImport.update({
    id: '/health-data',
    path: '/health-data',
    getParentRoute: () => dashboardDeprecatedPlayerPodRoute,
  } as any)

const dashboardDeprecatedPlayerPodFootballDataRoute =
  dashboardDeprecatedPlayerPodFootballDataImport.update({
    id: '/football-data',
    path: '/football-data',
    getParentRoute: () => dashboardDeprecatedPlayerPodRoute,
  } as any)

const dashboardDeprecatedPlayerPodSeasonsSeasonRoute =
  dashboardDeprecatedPlayerPodSeasonsSeasonImport.update({
    id: '/seasons/$season',
    path: '/seasons/$season',
    getParentRoute: () => dashboardDeprecatedPlayerPodRoute,
  } as any)

const dashboardDeprecatedPlayerPodMatchesMatchRoute =
  dashboardDeprecatedPlayerPodMatchesMatchImport.update({
    id: '/matches/$match',
    path: '/matches/$match',
    getParentRoute: () => dashboardDeprecatedPlayerPodRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/__dashboard': {
      id: '/__dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardImport
      parentRoute: typeof rootRoute
    }
    '/__dashboard/access-control': {
      id: '/__dashboard/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof dashboardAccessControlImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/access-history': {
      id: '/__dashboard/access-history'
      path: '/access-history'
      fullPath: '/access-history'
      preLoaderRoute: typeof dashboardAccessHistoryImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/inbox': {
      id: '/__dashboard/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof dashboardInboxImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/profile': {
      id: '/__dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof dashboardProfileImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/settings': {
      id: '/__dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsImport
      parentRoute: typeof dashboardImport
    }
    '/auth/_setup': {
      id: '/auth/_setup'
      path: ''
      fullPath: '/auth'
      preLoaderRoute: typeof AuthSetupImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/confirmation': {
      id: '/auth/confirmation'
      path: '/confirmation'
      fullPath: '/auth/confirmation'
      preLoaderRoute: typeof AuthConfirmationImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRouteImport
    }
    '/__dashboard/': {
      id: '/__dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/file/$url': {
      id: '/__dashboard/file/$url'
      path: '/file/$url'
      fullPath: '/file/$url'
      preLoaderRoute: typeof dashboardFileUrlImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/team/details': {
      id: '/__dashboard/team/details'
      path: '/team/details'
      fullPath: '/team/details'
      preLoaderRoute: typeof dashboardTeamDetailsImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/team/outsourcing': {
      id: '/__dashboard/team/outsourcing'
      path: '/team/outsourcing'
      fullPath: '/team/outsourcing'
      preLoaderRoute: typeof dashboardTeamOutsourcingImport
      parentRoute: typeof dashboardImport
    }
    '/auth/_setup/profile': {
      id: '/auth/_setup/profile'
      path: '/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthSetupProfileImport
      parentRoute: typeof AuthSetupImport
    }
    '/auth/_setup/team': {
      id: '/auth/_setup/team'
      path: '/team'
      fullPath: '/auth/team'
      preLoaderRoute: typeof AuthSetupTeamImport
      parentRoute: typeof AuthSetupImport
    }
    '/__dashboard/deprecated/player/$pod': {
      id: '/__dashboard/deprecated/player/$pod'
      path: '/deprecated/player/$pod'
      fullPath: '/deprecated/player/$pod'
      preLoaderRoute: typeof dashboardDeprecatedPlayerPodImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/player/$pod/$category': {
      id: '/__dashboard/player/$pod/$category'
      path: '/player/$pod/$category'
      fullPath: '/player/$pod/$category'
      preLoaderRoute: typeof dashboardPlayerPodCategoryImport
      parentRoute: typeof dashboardImport
    }
    '/__dashboard/deprecated/player/$pod/football-data': {
      id: '/__dashboard/deprecated/player/$pod/football-data'
      path: '/football-data'
      fullPath: '/deprecated/player/$pod/football-data'
      preLoaderRoute: typeof dashboardDeprecatedPlayerPodFootballDataImport
      parentRoute: typeof dashboardDeprecatedPlayerPodImport
    }
    '/__dashboard/deprecated/player/$pod/health-data': {
      id: '/__dashboard/deprecated/player/$pod/health-data'
      path: '/health-data'
      fullPath: '/deprecated/player/$pod/health-data'
      preLoaderRoute: typeof dashboardDeprecatedPlayerPodHealthDataImport
      parentRoute: typeof dashboardDeprecatedPlayerPodImport
    }
    '/__dashboard/deprecated/player/$pod/personal-data': {
      id: '/__dashboard/deprecated/player/$pod/personal-data'
      path: '/personal-data'
      fullPath: '/deprecated/player/$pod/personal-data'
      preLoaderRoute: typeof dashboardDeprecatedPlayerPodPersonalDataImport
      parentRoute: typeof dashboardDeprecatedPlayerPodImport
    }
    '/__dashboard/deprecated/player/$pod/tracking-data': {
      id: '/__dashboard/deprecated/player/$pod/tracking-data'
      path: '/tracking-data'
      fullPath: '/deprecated/player/$pod/tracking-data'
      preLoaderRoute: typeof dashboardDeprecatedPlayerPodTrackingDataImport
      parentRoute: typeof dashboardDeprecatedPlayerPodImport
    }
    '/__dashboard/deprecated/player/$pod/matches/$match': {
      id: '/__dashboard/deprecated/player/$pod/matches/$match'
      path: '/matches/$match'
      fullPath: '/deprecated/player/$pod/matches/$match'
      preLoaderRoute: typeof dashboardDeprecatedPlayerPodMatchesMatchImport
      parentRoute: typeof dashboardDeprecatedPlayerPodImport
    }
    '/__dashboard/deprecated/player/$pod/seasons/$season': {
      id: '/__dashboard/deprecated/player/$pod/seasons/$season'
      path: '/seasons/$season'
      fullPath: '/deprecated/player/$pod/seasons/$season'
      preLoaderRoute: typeof dashboardDeprecatedPlayerPodSeasonsSeasonImport
      parentRoute: typeof dashboardDeprecatedPlayerPodImport
    }
  }
}

// Create and export the route tree

interface AuthSetupRouteChildren {
  AuthSetupProfileRoute: typeof AuthSetupProfileRoute
  AuthSetupTeamRoute: typeof AuthSetupTeamRoute
}

const AuthSetupRouteChildren: AuthSetupRouteChildren = {
  AuthSetupProfileRoute: AuthSetupProfileRoute,
  AuthSetupTeamRoute: AuthSetupTeamRoute,
}

const AuthSetupRouteWithChildren = AuthSetupRoute._addFileChildren(
  AuthSetupRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSetupRoute: typeof AuthSetupRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmationRoute: typeof AuthConfirmationRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSetupRoute: AuthSetupRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmationRoute: AuthConfirmationRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface dashboardDeprecatedPlayerPodRouteChildren {
  dashboardDeprecatedPlayerPodFootballDataRoute: typeof dashboardDeprecatedPlayerPodFootballDataRoute
  dashboardDeprecatedPlayerPodHealthDataRoute: typeof dashboardDeprecatedPlayerPodHealthDataRoute
  dashboardDeprecatedPlayerPodPersonalDataRoute: typeof dashboardDeprecatedPlayerPodPersonalDataRoute
  dashboardDeprecatedPlayerPodTrackingDataRoute: typeof dashboardDeprecatedPlayerPodTrackingDataRoute
  dashboardDeprecatedPlayerPodMatchesMatchRoute: typeof dashboardDeprecatedPlayerPodMatchesMatchRoute
  dashboardDeprecatedPlayerPodSeasonsSeasonRoute: typeof dashboardDeprecatedPlayerPodSeasonsSeasonRoute
}

const dashboardDeprecatedPlayerPodRouteChildren: dashboardDeprecatedPlayerPodRouteChildren =
  {
    dashboardDeprecatedPlayerPodFootballDataRoute:
      dashboardDeprecatedPlayerPodFootballDataRoute,
    dashboardDeprecatedPlayerPodHealthDataRoute:
      dashboardDeprecatedPlayerPodHealthDataRoute,
    dashboardDeprecatedPlayerPodPersonalDataRoute:
      dashboardDeprecatedPlayerPodPersonalDataRoute,
    dashboardDeprecatedPlayerPodTrackingDataRoute:
      dashboardDeprecatedPlayerPodTrackingDataRoute,
    dashboardDeprecatedPlayerPodMatchesMatchRoute:
      dashboardDeprecatedPlayerPodMatchesMatchRoute,
    dashboardDeprecatedPlayerPodSeasonsSeasonRoute:
      dashboardDeprecatedPlayerPodSeasonsSeasonRoute,
  }

const dashboardDeprecatedPlayerPodRouteWithChildren =
  dashboardDeprecatedPlayerPodRoute._addFileChildren(
    dashboardDeprecatedPlayerPodRouteChildren,
  )

interface dashboardRouteChildren {
  dashboardAccessControlRoute: typeof dashboardAccessControlRoute
  dashboardAccessHistoryRoute: typeof dashboardAccessHistoryRoute
  dashboardInboxRoute: typeof dashboardInboxRoute
  dashboardProfileRoute: typeof dashboardProfileRoute
  dashboardSettingsRoute: typeof dashboardSettingsRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardFileUrlRoute: typeof dashboardFileUrlRoute
  dashboardTeamDetailsRoute: typeof dashboardTeamDetailsRoute
  dashboardTeamOutsourcingRoute: typeof dashboardTeamOutsourcingRoute
  dashboardDeprecatedPlayerPodRoute: typeof dashboardDeprecatedPlayerPodRouteWithChildren
  dashboardPlayerPodCategoryRoute: typeof dashboardPlayerPodCategoryRoute
}

const dashboardRouteChildren: dashboardRouteChildren = {
  dashboardAccessControlRoute: dashboardAccessControlRoute,
  dashboardAccessHistoryRoute: dashboardAccessHistoryRoute,
  dashboardInboxRoute: dashboardInboxRoute,
  dashboardProfileRoute: dashboardProfileRoute,
  dashboardSettingsRoute: dashboardSettingsRoute,
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardFileUrlRoute: dashboardFileUrlRoute,
  dashboardTeamDetailsRoute: dashboardTeamDetailsRoute,
  dashboardTeamOutsourcingRoute: dashboardTeamOutsourcingRoute,
  dashboardDeprecatedPlayerPodRoute:
    dashboardDeprecatedPlayerPodRouteWithChildren,
  dashboardPlayerPodCategoryRoute: dashboardPlayerPodCategoryRoute,
}

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(
  dashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthSetupRouteWithChildren
  '': typeof dashboardRouteWithChildren
  '/access-control': typeof dashboardAccessControlRoute
  '/access-history': typeof dashboardAccessHistoryRoute
  '/inbox': typeof dashboardInboxRoute
  '/profile': typeof dashboardProfileRoute
  '/settings': typeof dashboardSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirmation': typeof AuthConfirmationRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof dashboardIndexRoute
  '/file/$url': typeof dashboardFileUrlRoute
  '/team/details': typeof dashboardTeamDetailsRoute
  '/team/outsourcing': typeof dashboardTeamOutsourcingRoute
  '/auth/profile': typeof AuthSetupProfileRoute
  '/auth/team': typeof AuthSetupTeamRoute
  '/deprecated/player/$pod': typeof dashboardDeprecatedPlayerPodRouteWithChildren
  '/player/$pod/$category': typeof dashboardPlayerPodCategoryRoute
  '/deprecated/player/$pod/football-data': typeof dashboardDeprecatedPlayerPodFootballDataRoute
  '/deprecated/player/$pod/health-data': typeof dashboardDeprecatedPlayerPodHealthDataRoute
  '/deprecated/player/$pod/personal-data': typeof dashboardDeprecatedPlayerPodPersonalDataRoute
  '/deprecated/player/$pod/tracking-data': typeof dashboardDeprecatedPlayerPodTrackingDataRoute
  '/deprecated/player/$pod/matches/$match': typeof dashboardDeprecatedPlayerPodMatchesMatchRoute
  '/deprecated/player/$pod/seasons/$season': typeof dashboardDeprecatedPlayerPodSeasonsSeasonRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthSetupRouteWithChildren
  '/access-control': typeof dashboardAccessControlRoute
  '/access-history': typeof dashboardAccessHistoryRoute
  '/inbox': typeof dashboardInboxRoute
  '/profile': typeof dashboardProfileRoute
  '/settings': typeof dashboardSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirmation': typeof AuthConfirmationRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof dashboardIndexRoute
  '/file/$url': typeof dashboardFileUrlRoute
  '/team/details': typeof dashboardTeamDetailsRoute
  '/team/outsourcing': typeof dashboardTeamOutsourcingRoute
  '/auth/profile': typeof AuthSetupProfileRoute
  '/auth/team': typeof AuthSetupTeamRoute
  '/deprecated/player/$pod': typeof dashboardDeprecatedPlayerPodRouteWithChildren
  '/player/$pod/$category': typeof dashboardPlayerPodCategoryRoute
  '/deprecated/player/$pod/football-data': typeof dashboardDeprecatedPlayerPodFootballDataRoute
  '/deprecated/player/$pod/health-data': typeof dashboardDeprecatedPlayerPodHealthDataRoute
  '/deprecated/player/$pod/personal-data': typeof dashboardDeprecatedPlayerPodPersonalDataRoute
  '/deprecated/player/$pod/tracking-data': typeof dashboardDeprecatedPlayerPodTrackingDataRoute
  '/deprecated/player/$pod/matches/$match': typeof dashboardDeprecatedPlayerPodMatchesMatchRoute
  '/deprecated/player/$pod/seasons/$season': typeof dashboardDeprecatedPlayerPodSeasonsSeasonRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/__dashboard': typeof dashboardRouteWithChildren
  '/__dashboard/access-control': typeof dashboardAccessControlRoute
  '/__dashboard/access-history': typeof dashboardAccessHistoryRoute
  '/__dashboard/inbox': typeof dashboardInboxRoute
  '/__dashboard/profile': typeof dashboardProfileRoute
  '/__dashboard/settings': typeof dashboardSettingsRoute
  '/auth/_setup': typeof AuthSetupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirmation': typeof AuthConfirmationRoute
  '/auth/login': typeof AuthLoginRoute
  '/__dashboard/': typeof dashboardIndexRoute
  '/__dashboard/file/$url': typeof dashboardFileUrlRoute
  '/__dashboard/team/details': typeof dashboardTeamDetailsRoute
  '/__dashboard/team/outsourcing': typeof dashboardTeamOutsourcingRoute
  '/auth/_setup/profile': typeof AuthSetupProfileRoute
  '/auth/_setup/team': typeof AuthSetupTeamRoute
  '/__dashboard/deprecated/player/$pod': typeof dashboardDeprecatedPlayerPodRouteWithChildren
  '/__dashboard/player/$pod/$category': typeof dashboardPlayerPodCategoryRoute
  '/__dashboard/deprecated/player/$pod/football-data': typeof dashboardDeprecatedPlayerPodFootballDataRoute
  '/__dashboard/deprecated/player/$pod/health-data': typeof dashboardDeprecatedPlayerPodHealthDataRoute
  '/__dashboard/deprecated/player/$pod/personal-data': typeof dashboardDeprecatedPlayerPodPersonalDataRoute
  '/__dashboard/deprecated/player/$pod/tracking-data': typeof dashboardDeprecatedPlayerPodTrackingDataRoute
  '/__dashboard/deprecated/player/$pod/matches/$match': typeof dashboardDeprecatedPlayerPodMatchesMatchRoute
  '/__dashboard/deprecated/player/$pod/seasons/$season': typeof dashboardDeprecatedPlayerPodSeasonsSeasonRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | ''
    | '/access-control'
    | '/access-history'
    | '/inbox'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/auth/confirmation'
    | '/auth/login'
    | '/'
    | '/file/$url'
    | '/team/details'
    | '/team/outsourcing'
    | '/auth/profile'
    | '/auth/team'
    | '/deprecated/player/$pod'
    | '/player/$pod/$category'
    | '/deprecated/player/$pod/football-data'
    | '/deprecated/player/$pod/health-data'
    | '/deprecated/player/$pod/personal-data'
    | '/deprecated/player/$pod/tracking-data'
    | '/deprecated/player/$pod/matches/$match'
    | '/deprecated/player/$pod/seasons/$season'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/access-control'
    | '/access-history'
    | '/inbox'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/auth/confirmation'
    | '/auth/login'
    | '/'
    | '/file/$url'
    | '/team/details'
    | '/team/outsourcing'
    | '/auth/profile'
    | '/auth/team'
    | '/deprecated/player/$pod'
    | '/player/$pod/$category'
    | '/deprecated/player/$pod/football-data'
    | '/deprecated/player/$pod/health-data'
    | '/deprecated/player/$pod/personal-data'
    | '/deprecated/player/$pod/tracking-data'
    | '/deprecated/player/$pod/matches/$match'
    | '/deprecated/player/$pod/seasons/$season'
  id:
    | '__root__'
    | '/auth'
    | '/__dashboard'
    | '/__dashboard/access-control'
    | '/__dashboard/access-history'
    | '/__dashboard/inbox'
    | '/__dashboard/profile'
    | '/__dashboard/settings'
    | '/auth/_setup'
    | '/auth/callback'
    | '/auth/confirmation'
    | '/auth/login'
    | '/__dashboard/'
    | '/__dashboard/file/$url'
    | '/__dashboard/team/details'
    | '/__dashboard/team/outsourcing'
    | '/auth/_setup/profile'
    | '/auth/_setup/team'
    | '/__dashboard/deprecated/player/$pod'
    | '/__dashboard/player/$pod/$category'
    | '/__dashboard/deprecated/player/$pod/football-data'
    | '/__dashboard/deprecated/player/$pod/health-data'
    | '/__dashboard/deprecated/player/$pod/personal-data'
    | '/__dashboard/deprecated/player/$pod/tracking-data'
    | '/__dashboard/deprecated/player/$pod/matches/$match'
    | '/__dashboard/deprecated/player/$pod/seasons/$season'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  dashboardRoute: typeof dashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  dashboardRoute: dashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/auth",
        "/__dashboard"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/_setup",
        "/auth/callback",
        "/auth/confirmation",
        "/auth/login"
      ]
    },
    "/__dashboard": {
      "filePath": "__dashboard.tsx",
      "children": [
        "/__dashboard/access-control",
        "/__dashboard/access-history",
        "/__dashboard/inbox",
        "/__dashboard/profile",
        "/__dashboard/settings",
        "/__dashboard/",
        "/__dashboard/file/$url",
        "/__dashboard/team/details",
        "/__dashboard/team/outsourcing",
        "/__dashboard/deprecated/player/$pod",
        "/__dashboard/player/$pod/$category"
      ]
    },
    "/__dashboard/access-control": {
      "filePath": "__dashboard/access-control.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/access-history": {
      "filePath": "__dashboard/access-history.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/inbox": {
      "filePath": "__dashboard/inbox.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/profile": {
      "filePath": "__dashboard/profile.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/settings": {
      "filePath": "__dashboard/settings.tsx",
      "parent": "/__dashboard"
    },
    "/auth/_setup": {
      "filePath": "auth/_setup.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_setup/profile",
        "/auth/_setup/team"
      ]
    },
    "/auth/callback": {
      "filePath": "auth/callback.tsx",
      "parent": "/auth"
    },
    "/auth/confirmation": {
      "filePath": "auth/confirmation.tsx",
      "parent": "/auth"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/__dashboard/": {
      "filePath": "__dashboard/index.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/file/$url": {
      "filePath": "__dashboard/file/$url.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/team/details": {
      "filePath": "__dashboard/team/details.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/team/outsourcing": {
      "filePath": "__dashboard/team/outsourcing.tsx",
      "parent": "/__dashboard"
    },
    "/auth/_setup/profile": {
      "filePath": "auth/_setup.profile.tsx",
      "parent": "/auth/_setup"
    },
    "/auth/_setup/team": {
      "filePath": "auth/_setup.team.tsx",
      "parent": "/auth/_setup"
    },
    "/__dashboard/deprecated/player/$pod": {
      "filePath": "__dashboard/deprecated/player/$pod.tsx",
      "parent": "/__dashboard",
      "children": [
        "/__dashboard/deprecated/player/$pod/football-data",
        "/__dashboard/deprecated/player/$pod/health-data",
        "/__dashboard/deprecated/player/$pod/personal-data",
        "/__dashboard/deprecated/player/$pod/tracking-data",
        "/__dashboard/deprecated/player/$pod/matches/$match",
        "/__dashboard/deprecated/player/$pod/seasons/$season"
      ]
    },
    "/__dashboard/player/$pod/$category": {
      "filePath": "__dashboard/player/$pod/$category.tsx",
      "parent": "/__dashboard"
    },
    "/__dashboard/deprecated/player/$pod/football-data": {
      "filePath": "__dashboard/deprecated/player/$pod/football-data.tsx",
      "parent": "/__dashboard/deprecated/player/$pod"
    },
    "/__dashboard/deprecated/player/$pod/health-data": {
      "filePath": "__dashboard/deprecated/player/$pod/health-data.tsx",
      "parent": "/__dashboard/deprecated/player/$pod"
    },
    "/__dashboard/deprecated/player/$pod/personal-data": {
      "filePath": "__dashboard/deprecated/player/$pod/personal-data.tsx",
      "parent": "/__dashboard/deprecated/player/$pod"
    },
    "/__dashboard/deprecated/player/$pod/tracking-data": {
      "filePath": "__dashboard/deprecated/player/$pod/tracking-data.tsx",
      "parent": "/__dashboard/deprecated/player/$pod"
    },
    "/__dashboard/deprecated/player/$pod/matches/$match": {
      "filePath": "__dashboard/deprecated/player/$pod/matches.$match.tsx",
      "parent": "/__dashboard/deprecated/player/$pod"
    },
    "/__dashboard/deprecated/player/$pod/seasons/$season": {
      "filePath": "__dashboard/deprecated/player/$pod/seasons.$season.tsx",
      "parent": "/__dashboard/deprecated/player/$pod"
    }
  }
}
ROUTE_MANIFEST_END */
